#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

cd "${SCRIPT_DIR}/.."

godot -d -s --path "." addons/gut/gut_cmdln.gd -gconfig .gutconfig.test.json
